blockLists:
  - https://raw.githubusercontent.com/bwoff11/blocklists/main/ads.yml
  - https://raw.githubusercontent.com/bwoff11/blocklists/main/malware.yml
  - https://raw.githubusercontent.com/bwoff11/blocklists/main/other.yml
  - https://raw.githubusercontent.com/bwoff11/blocklists/main/tracking.yml

cache:
  enabled: true
  pruneInterval: 60

local:
  standard:
    - domain: "example.com"
      type: "A"
      value: "10.10.10.10"
      ttl: 3600
    - domain: "example.com"
      type: "AAAA"
      value: "2606:2800:220:1:248:1893:25c8:1946"
      ttl: 3600
    - domain: "www.example.com"
      type: "CNAME"
      value: "example.com"
      ttl: 3600
    - domain: "example.com"
      type: "TXT"
      value: "v=spf1 include:_spf.example.com ~all"
      ttl: 3600

metrics:
  enabled: true
  route: "/metrics"
  port: 9091

protocols:
  udp:
    enabled: true
    port: 1053
  tcp:
    enabled: true
    port: 1053
  dot:
    enabled: false
    port: 853
    tlsCertFile: "path/to/dns_cert.pem"
    tlsKeyFile: "path/to/dns_key.pem"
    strictSNI: false

upstream:
  strategy: "random" # Options: random, roundRobin, sequential, latency
  servers:
  - name: "Google"
    ip: "8.8.8.8"
    port: 53
    timeout: 5
  #- name: "Cloudflare"
  #  ip: "1.1.1.1"
  #  port: 53
  #  timeout: 5