web:
  enabled: true
  port: 8080
  tls:
    enabled: false
    certFile: "path/to/cert.pem"
    keyFile: "path/to/key.pem"

logging:
  level: "info"
  output: "stdout" # Options: stdout, file
  filePath: "path/to/logfile" # If output is file

metrics:
  enabled: true
  route: "/metrics"
  port: 9091

dns:
  TTL: 3600
  maxMessageSize: 4096

  cache:
    enabled: true
    size: 10000 # Number of entries to cache
    ttl: "300s"
    purgeInterval: "60s"

  upstream:
    enabled: true
    timeout: "5s"
    strategy: "random" # Options: random, roundRobin, sequential, latency
    servers:
    - "8.8.8.8"
    - "8.8.4.4"
    - "1.1.1.1"

  protocols:
    udp:
      enabled: true
      port: 1053
    tcp:
      enabled: true
      port: 1053
    dot:
      enabled: false
      port: 853
      tlsCertFile: "path/to/dns_cert.pem"
      tlsKeyFile: "path/to/dns_key.pem"
      strictSNI: false # Enforce strict Server Name Indication checking

  local:
    - domain: "example.com"
      type: "A"
      value: "1.2.3.4"
      ttl: 3600
    - domain: "example.net"
      type: "AAAA"
      value: "2001:db8::1"
      ttl: 3600
    - domain: "test.example.com"
      type: "CNAME"
      value: "example.com"
      ttl: 3600

# --- Unimplemented ---

  rateLimiting:
    enabled: false
    requestsPerSecond: 10
    burstSize: 20 # Maximum number of requests that can be allowed in a burst

  blockList:
    local:
      enabled: false
      sources:
        - "path/to/blocklist1"
        - "path/to/blocklist2"
    remote:
      enabled: false
      sources:
        - "github.com/bwoff11/blocklists/ads.txt"
        - "github.com/bwoff11/blocklists/malware.txt"
